services:
  db:
    image: postgres:latest 
    env_file:
      - .env    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql 
    networks:
      - app_network
    ports:
      - "5432:5432"
    restart: always

  lumen:
    build:
      context: ./lumem-webhook-api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

  flask:
    build:
      context: ./HookVison
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:      
      - POSTGRES_DB= ${POSTGRES_DB}       
      - POSTGRES_USER= ${POSTGRES_USER}    
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - URL_DB=${URL_DB}
      - SECRET_KEY_COOKIE=${SECRET_KEY_COOKIE}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network
    restart: always

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
