services:
  db:
    image: postgres:latest 
    environment:
      POSTGRES_DB: ${DB}        
      POSTGRES_USER: ${USER}    
      POSTGRES_PASSWORD: ${PASSWORD} 
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql 
    networks:
      - app_network
    ports:
      - "5432:5432"
    restart: always

  flask:
    build:
      context: ./HookVison
      dockerfile: Dockerfile
    environment:      
      - POSTGRES_DB= ${DB}        
      - POSTGRES_USER= ${USER}    
      - POSTGRES_PASSWORD= ${PASSWORD} 
      - URL_DB=${URL_DB}  # Variável usada no Flask (SETA SSIM: NOME DA VARIAVEL DO JEITO QUE É CHAMADA NO PROJETO E VARIAVEL QUE VEM DA ENV)
      - SECRET_KEY_COOKIE=${SECRET_KEY_COOKIE}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  lumen:
    build:
      context: ./lumem-webhook-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
