"""Initial migration.

Revision ID: 259ad33b8bcf
Revises: 
Create Date: 2024-11-30 13:53:48.801632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259ad33b8bcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Float(precision=2), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('parcelas', sa.String(length=50), nullable=True),
    sa.Column('status_no_sistema', sa.String(length=50), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('pagamentos')
    # ### end Alembic commands ###
